[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wgdashboardapi"
version = "0.1.0"
description = "Async Python SDK for WGDashboard"
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
dependencies = ["httpx", "pydantic"]

[tool.hatch.build.targets.wheel]
packages = ["src/wgdashboard"]